#!/bin/bash
for file in accessdenied/data/secret/*.in
do
dir=`dirname $file`
out=$dir/`basename -s .in $file`.ans
echo Trying case $file out $out
./intrunner accessdenied/output_validators/validate/validate_out \
	$file \
	$out \
	feedback \
	res333.xml accessdenied/submissions/wrong_answer/forget_uppercase_letter
if ! grep -q Accepted res333.xml 
then
	cat res333.xml
	read a
fi
done
