#!/bin/bash
./intrunner.sh accessdenied/output_validators/validate/validate_out \
	accessdenied/data/secret/secret__88-all_chars_1.in \
	accessdenied/data/secret/secret__88-all_chars_1.ans \
	feedback \
	res333.xml ./a 
cat res333.xml
