#!/bin/bash
./pc2sandbox_interactive.sh 64 2 accessdenied/output_validators/validate/validate_out \
	accessdenied/data/secret/secret__88-all_chars_1.in \
	accessdenied/data/secret/secret__88-all_chars_1.ans \
	1 \
	./m 
cat tmp_results.xml
