#!/bin/bash
n=1
for file in accessdenied/data/secret/*.in
do
	of=`echo "$file" | sed -e 's/.in$/.ans/'`
	./pc2_interactive.sh accessdenied/output_validators/validate/validate_out \
		$file $of \
		$n \
		./a 

	if ! grep -i accepted interactive_results.xml >/dev/null
	then
		echo $file
		cat interactive_results.xml
	fi
	n=$((n+1))
done
