#!/bin/bash
REPOS=$HOME/repos


if test $# -ne 1
then
	echo Usage: $0 reponame
	exit 1
fi
r=$1
if test ! -d ${REPOS}
then
	echo $0: Can not find the repos folder: $REPOS
	exit 3
fi
cd ${REPOS}
if test ! -d $r
then
	echo $0: No repo: ${REPOS}/$r does not exist
	exit 2
fi

src=$r
dst=repos

. get_judge_info


if IsSameHost ${PC2SERVER}
then
	echo Skipping myself as server: $PC2SERVER...
else
	hostlist="${SERVER_USER}@${PC2SERVER}"
fi

for j in ${JUDGE_LIST}
do
	if IsSameHost "$j"
	then
		echo Skipping myself: $j
		continue
	fi
	hostlist=$hostlist" $JUDGE_USER@$j"
done
for host in ${hostlist}
do
	echo Rsyncing "$src" to "$host:$dst" 
	rsync -4ae ssh "$src" "$host:$dst"
done
