#!/bin/bash
if [[ $0 == *StopJudg* ]]
then
	cmd=RemoteStopJudgeByNumber.sh
	str=Stopp
else
	cmd=RemoteStartJudgeByNumber.sh
	str=Start
fi
if test $# -eq 1
then
	jcnt=$1
else
	jcnt=100
fi
. get_judge_info
cnt=0
for j in ${JUDGE_LIST}
do
	host="$JUDGE_USER@$j"
	judge=${j#"$JUDGE_PREFIX"}
	echo '***************' ${str}ing Judge $judge on $host '******************'
	ssh -4 $host bash -l $cmd $judge
	cnt=$((cnt+1))
	if test $cnt -ge $jcnt
	then
		break
	fi
	sleep 1
done

