#!/bin/bash
. get_judge_info
if [[ $0 == *StopJudg* ]]
then
	cmd=RemoteStopJudgeByNumber.sh
else
	cmd=RemoteStartJudgeByNumber.sh
fi
if test $# -eq 1
then
	jcnt=$1
else
	jcnt=100
fi
cnt=0
for j in ${JUDGE_LIST}
do
	host="$JUDGE_USER@$j"
	judge=${j#"$JUDGE_PREFIX"}
	echo '***************' Starting Judge $judge on $host '******************'
	ssh -4 $host "~/repos/icpc-utils/nacbin/$cmd" $judge
	cnt=$((cnt+1))
	if test $cnt -ge $jcnt
	then
		break
	fi
	sleep 1
done

