#!/bin/bash
if test $# -ne 2
then
	echo Usage: $0 source dest
	exit 1
fi
src=$1
dst=$2
. judge_setup_env

for j in ${JUDGE_LIST}
do
	echo Copying "$src" to "root@pc2-aj$j$URLBASE:$dst"
	scp -4 -p "$src" "root@pc2-aj$j$URLBASE:$dst"
done
